# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Pages
on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wranders/markdown-to-pages-action@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #   - run: cp ./images ./dist/images/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
