# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Pages
on:
  workflow_dispatch:
  push:
    # tags:
    #   - v[0-9]+.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wranders/markdown-to-pages-action@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #   - run: cp ./images ./dist/images/
      - name: publish to pgs
        uses: picosh/pgs-action@v3
        with:
          user: erock
          key: ${{ secrets.PRIVATE_KEY }}
          # trailing slash is important (we use rsync)
          src: "./dist/"
          # update or create a new project on-the-fly
          project: "pastol"

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - uses: actions/deploy-pages@v4
  #       id: deployment
